let projects = [
    {
        "name": "Declare Martial Law",
        "time": 0,
        "cost": {
            "loyalty": 4,
            "warriors": 0,
            "order": 0,
            "reverence": 2,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        },
        "text": "Strict curfews, limited movements of the civilians, and a slew of other restrictions on civilian activity in Gornath. These measures have not been used since the days of Chief Bazor under the rule of the Demon Kings...",
        "return": {
            "loyalty": 0,
            "warriors": 3,
            "order": 6,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ['Martial Law Declared!', "You're in trouble now..."],
        "callback": ``
    }, 
    {
        "name": "Take Out a Loan",
        "time": 0,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        },
        "text": "The mangy kobold has offered to give us a generous loan. The only question is when he'll expect it to be paid back...",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 5,
            "intel": 0,
        }, 
        "declaration": ["Debt Acquired", "(And some pocket change)"],
        "callback": ""
    }, 
    {
        "name": "Gild Bokaz' Throne",
        "requires": "",
        "time": 0,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 3,
            "intel": 0,
        },
        "text": "If we want the chief to be respected, we should make that worn and cracked stone throne he sits on look a little more impressive.",
        "return": {
            "loyalty": 1,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Throne Blinged Out","Trakumir would be envious!"],
        "callback": ""
    },
    {
        "name": "Upgrade Armour",
        "requires": "",
        "time": 5,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 5,
            "wealth": 4,
            "intel": 0,
        },
        "text": "Tiren wants to work on refining the armour that our warriors are equipped with. This will boost their AC from 14 to 16",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Armour Upgraded", "(It's no longer painted red)"],
        "callback": ""
    },
    {
        "name": "Upgrade Weapons",
        "requires": "",
        "time": 5,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 7,
            "wealth": 2,
            "intel": 0,
        },
        "text": "Our Warriors are equipped with basic weapons, but we can do better. With some work, Tiren can boost their damage dice from a d6 to a d12.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Weapons Upgraded", "(Now with extra spikes)"],
        "callback": ""
    },
    {
        "name": "Ionian Fortifications",
        "requires": "",
        "time": 5,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 4,
            "wealth": 4,
            "intel": 0,
        },
        "text": "M'rin, the paladin of Ionis that has been tending to the temple of Ionis wants to fortify the temple of Ionis. He thinks it will make a good place to keep our civilians safe during the fighting.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 1,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Temple Fortified","They'll be nice and safe now"],
        "callback": ""
    },
    {
        "name": "Astarian Enchantments",
        "requires": "",
        "time": 5,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 5,
            "intel": 0,
        },
        "text": "Xaltor the Wise would like to invest in some arcane inks with which to place enchantments and wards upon the Shrine of Astaris. It's not exactly high priority, but it could strengthen the faith of the people in Astaris.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 2,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Shrine Enchanted","It's all very impressive looking now"],
        "callback": ""
    },
    {
        "name": "A Weapon for Corpus",
        "requires": "unworthy",
        "time": 6,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 1,
            "salvage": 10,
            "wealth": 10,
            "intel": 0,
        },
        "text": "Unworthy has promised Corpus a weapon worthy of killing demonic hordes. We just need to make sure he's well supplied.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Weapon Manufactured","Time to kill some fucking demons!"],
        "callback": ""
    }, 
    {
        "name": "Magimecha Enchantment",
        "requires": "unworthy",
        "time": 6,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 1,
            "salvage": 3,
            "wealth": 8,
            "intel": 0,
        },
        "text": "Unworthy has experience enchanting magimecha weapons. With his skills, we could improve our weapons. All magimecha weapons, both those used by the party, and those used by the Gornathi will become +1.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Weapons Enhanced", "(With vile Iron Sorcery)"],
        "callback": ""
    }, 
    {
        "name": "Minefield",
        "requires": "",
        "time": 6,
        "cost": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 8,
            "wealth": 0,
            "intel": 0,
        },
        "text": "Using Tanwin the Fabricator's experience with magimecha crafting, we could set up magimecha minefields at the entrances to Gornath, aiding our defence of the city when the time comes.",
        "return": {
            "loyalty": 0,
            "warriors": 0,
            "order": 0,
            "reverence": 0,
            "salvage": 0,
            "wealth": 0,
            "intel": 0,
        }, 
        "declaration": ["Entrances Mined","(Just don't forget they're there...)"],
        "callback": ""
    }
]